// Generated by CoffeeScript 1.6.2
(function() {
  var compile, markdown;

  compile = require('./compile.js');

  markdown = require('markdown').markdown;

  module.exports = function(item, cb) {
    var fun, result;

    fun = compile(item);
    result = fun({
      title: item.header.title,
      description: item.header.description,
      content: markdown.toHTML(item.body),
      dateString: item.dateString
    });
    return cb(null, result);
  };

}).call(this);
