// Generated by CoffeeScript 1.6.2
(function() {
  var compile, getLocals;

  compile = require('./compile.js');

  getLocals = require('./getLocals.js');

  module.exports = function(item, callback) {
    var jadeCompile, result;

    jadeCompile = compile(item);
    result = jadeCompile(getLocals(item));
    return callback(null, result);
  };

}).call(this);
