// Generated by CoffeeScript 1.6.2
(function() {
  var compile, https, pickup;

  https = require('https');

  compile = require('./compile.js');

  pickup = require('pickup');

  module.exports = function(item, cb) {
    var articles, parser, url;

    url = item.header.url;
    parser = pickup();
    articles = [];
    https.get(url, function(res) {
      return res.pipe(parser);
    });
    parser.on('error', function(er) {
      return cb(er);
    });
    parser.on('entry', function(article) {
      return articles.push(article);
    });
    return parser.on('finish', function() {
      var jadeCompile, result;

      jadeCompile = compile(item);
      result = jadeCompile({
        articles: articles
      });
      return cb(null, result);
    });
  };

}).call(this);
