// Generated by CoffeeScript 1.6.2
(function() {
  var bake, channel, compile, entry, get_articles, locals;

  compile = require('./compile.js');

  get_articles = require('./getArticles.js');

  module.exports = function(item, cb) {
    return get_articles(item, -1, function(er, entries) {
      if (er != null) {
        return cb(er);
      }
      return bake(item, entries, function(er, html) {
        return cb(er, html);
      });
    });
  };

  channel = function(it, date) {
    return {
      pubDate: date,
      title: it.header.title,
      href: it.header.link + it.header.name,
      link: it.header.link,
      description: it.header.description
    };
  };

  entry = function(a) {
    return {
      title: a.title,
      description: a.description,
      content: ['<![CDATA[', a.content, ']>'].join(''),
      link: a.link,
      pubDate: a.pubDate
    };
  };

  locals = function(item, articles) {
    var a;

    return {
      channel: channel(item, articles[0].pubDate),
      entries: (function() {
        var _i, _len, _results;

        _results = [];
        for (_i = 0, _len = articles.length; _i < _len; _i++) {
          a = articles[_i];
          _results.push(entry(a));
        }
        return _results;
      })()
    };
  };

  bake = function(item, articles, cb) {
    var fun, res;

    fun = compile(item);
    res = fun(locals(item, articles));
    return cb(null, res);
  };

}).call(this);
