// Generated by CoffeeScript 1.6.2
(function() {
  var assert, compile, fm, get_entries, process;

  compile = require('./compile.js');

  get_entries = require('./getArticles.js');

  assert = require('assert');

  module.exports = function(item, cb) {
    return get_entries(item, -1, function(er, entries) {
      if (er != null) {
        return cb(er);
      }
      return process(item, entries, function(er, html) {
        return cb(er, html);
      });
    });
  };

  fm = function(entry) {
    entry.content = ['<![CDATA[', entry.content, ']>'].join('');
    return entry;
  };

  process = function(item, entries, cb) {
    var c, entry, locals, pubDate, res;

    pubDate = entries[0].pubDate;
    locals = {
      channel: {
        pubDate: pubDate,
        title: item.header.title,
        href: item.header.link + item.header.name,
        link: item.header.link,
        description: item.header.description
      },
      entries: (function() {
        var _i, _len, _results;

        _results = [];
        for (_i = 0, _len = entries.length; _i < _len; _i++) {
          entry = entries[_i];
          _results.push(fm(entry));
        }
        return _results;
      })()
    };
    c = compile(item);
    res = c(locals);
    assert(!locals.items);
    return cb(null, res);
  };

}).call(this);
