// Generated by CoffeeScript 1.6.2
(function() {
  var compile, qs, request, twitter;

  request = require('request');

  compile = require('./compile.js');

  twitter = require('twitter-text');

  qs = require('querystring');

  module.exports = function(item, callback) {
    var ACCESS_TOKEN, ACCESS_TOKEN_SECRET, CONSUMER_KEY, CONSUMER_SECRET, oauth, options, params, screen_name, url, _ref, _ref1;

    _ref = item.header, url = _ref.url, screen_name = _ref.screen_name;
    _ref1 = process.env, CONSUMER_KEY = _ref1.CONSUMER_KEY, CONSUMER_SECRET = _ref1.CONSUMER_SECRET, ACCESS_TOKEN = _ref1.ACCESS_TOKEN, ACCESS_TOKEN_SECRET = _ref1.ACCESS_TOKEN_SECRET;
    oauth = {
      consumer_key: CONSUMER_KEY,
      consumer_secret: CONSUMER_SECRET,
      token: ACCESS_TOKEN,
      token_secret: ACCESS_TOKEN_SECRET
    };
    params = {
      screen_name: screen_name,
      count: 1
    };
    options = {
      url: url += qs.stringify(params),
      oauth: oauth
    };
    return request(options, function(err, resp, body) {
      var jadeCompile, result, text, tweet, tweets;

      if (err != null) {
        return callback(err);
      }
      tweets = JSON.parse(body);
      tweet = tweets[0];
      if (!((tweet != null) && (tweet.text != null))) {
        return callback(new Error('No tweet'));
      }
      text = twitter.autoLink(tweet.text, {
        urlEntities: tweet.entities.urls
      });
      jadeCompile = compile(item);
      result = jadeCompile({
        text: text
      });
      return callback(null, result);
    });
  };

}).call(this);
